package dev.recordable;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.LinkOption;
import java.nio.file.OpenOption;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

public final class ChapterManager {
	private ChapterManager() {
	}

	private static String stem(Path videoFile) {
		String name = videoFile.getFileName().toString();
		int dot = name.lastIndexOf(46);
		return dot > 0 ? name.substring(0, dot) : name;
	}

	public static String formatTimestamp(long millis) {
		long totalSeconds = Math.max(0L, millis) / 1000L;
		long h = totalSeconds / 3600L;
		long m = totalSeconds % 3600L / 60L;
		long s = totalSeconds % 60L;
		return String.format(Locale.ROOT, "%02d:%02d:%02d", h, m, s);
	}

	public static Path writeChapterTextFile(Path videoFile, List<RecordingBookmark> markers) {
		if (videoFile != null && markers != null && !markers.isEmpty()) {
			Path out = videoFile.resolveSibling(stem(videoFile) + "_chapters.txt");
			List<String> lines = new ArrayList();
			lines.add("Chapters / Markers for: " + videoFile.getFileName());
			lines.add("Generated by Record-able");
			lines.add("Tip: paste these into a YouTube description for clickable chapters.");
			lines.add("");
			int idx = 1;

			for (RecordingBookmark m : markers) {
				lines.add(formatTimestamp(m.timestampMs()) + "  " + safeLabel(m.description(), idx));
				idx++;
			}

			try {
				Files.write(out, lines, StandardCharsets.UTF_8, StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING, StandardOpenOption.WRITE);
				return out;
			} catch (IOException var7) {
				RecordableMod.LOGGER.warn("ChapterManager: failed to write chapters file: {}", var7.getMessage());
				return null;
			}
		} else {
			return null;
		}
	}

	public static Path writeFfmetadataFile(Path videoFile, List<RecordingBookmark> markers, long totalDurationMs) {
		if (videoFile != null && markers != null && !markers.isEmpty()) {
			Path out = videoFile.resolveSibling(stem(videoFile) + "_ffmeta.txt");
			StringBuilder sb = new StringBuilder();
			sb.append(";FFMETADATA1\n");
			int idx = 1;

			for (int i = 0; i < markers.size(); i++) {
				long start = Math.max(0L, ((RecordingBookmark)markers.get(i)).timestampMs());
				long end;
				if (i + 1 < markers.size()) {
					end = Math.max(start + 1L, ((RecordingBookmark)markers.get(i + 1)).timestampMs());
				} else {
					end = Math.max(start + 1L, totalDurationMs > 0L ? totalDurationMs : start + 1000L);
				}

				sb.append("[CHAPTER]\n");
				sb.append("TIMEBASE=1/1000\n");
				sb.append("START=").append(start).append('\n');
				sb.append("END=").append(end).append('\n');
				sb.append("title=").append(escapeMeta(safeLabel(((RecordingBookmark)markers.get(i)).description(), idx))).append('\n');
				idx++;
			}

			try {
				Files.write(
					out,
					sb.toString().getBytes(StandardCharsets.UTF_8),
					new OpenOption[]{StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING, StandardOpenOption.WRITE}
				);
				return out;
			} catch (IOException var12) {
				RecordableMod.LOGGER.warn("ChapterManager: failed to write ffmetadata file: {}", var12.getMessage());
				return null;
			}
		} else {
			return null;
		}
	}

	public static Path embedChapters(Path videoFile, List<RecordingBookmark> markers, long totalDurationMs) {
		Path meta = writeFfmetadataFile(videoFile, markers, totalDurationMs);
		if (meta == null) {
			return null;
		} else {
			String ffmpeg = FfmpegBundleManager.getBundledFfmpegPath();
			if (ffmpeg != null && !ffmpeg.isBlank()) {
				String name = videoFile.getFileName().toString();
				int dot = name.lastIndexOf(46);
				String ext = dot > 0 ? name.substring(dot) : ".mkv";
				Path out = videoFile.resolveSibling(stem(videoFile) + "_chaptered" + ext);

				try {
					List<String> cmd = new ArrayList();
					cmd.add(ffmpeg);
					cmd.add("-y");
					cmd.add("-i");
					cmd.add(videoFile.toString());
					cmd.add("-i");
					cmd.add(meta.toString());
					cmd.add("-map_metadata");
					cmd.add("1");
					cmd.add("-map_chapters");
					cmd.add("1");
					cmd.add("-codec");
					cmd.add("copy");
					cmd.add(out.toString());
					Process p = new ProcessBuilder(cmd).redirectErrorStream(true).start();
					InputStream in = p.getInputStream();

					try {
						in.readAllBytes();
					} catch (Throwable var16) {
						if (in != null) {
							try {
								in.close();
							} catch (Throwable var15) {
								var16.addSuppressed(var15);
							}
						}

						throw var16;
					}

					if (in != null) {
						in.close();
					}

					int code = p.waitFor();
					if (code == 0 && Files.isRegularFile(out, new LinkOption[0])) {
						return out;
					}

					RecordableMod.LOGGER.warn("ChapterManager: embed exited with code {}", code);
					Files.deleteIfExists(out);
				} catch (Exception var17) {
					RecordableMod.LOGGER.warn("ChapterManager: embed failed: {}", var17.getMessage());
				}

				return null;
			} else {
				RecordableMod.LOGGER.warn("ChapterManager: ffmpeg unavailable, cannot embed chapters");
				return null;
			}
		}
	}

	private static String safeLabel(String desc, int idx) {
		return desc != null && !desc.isBlank() ? desc.trim() : "Chapter " + idx;
	}

	private static String escapeMeta(String s) {
		return s.replace("\\", "\\\\").replace("=", "\\=").replace(";", "\\;").replace("#", "\\#").replace("\n", " ");
	}
}
